Error in <TSystem::ExpandFileName>: input: ${HOME}/rootlogon.C, output: ${HOME}/rootlogon.C
Error in <TSystem::ExpandFileName>: input: /data/users/snabili/CalVision/DD4HEP_simulation_05282024/DD4hep/examples/SingleCrystal_cosmic_ray/compact/./${HOME}/rootlogon.C, output: /data/users/snabili/CalVision/DD4HEP_simulation_05282024/DD4hep/examples/SingleCrystal_cosmic_ray/compact/./${HOME}/rootlogon.C
Error in <TSystem::ExpandFileName>: input: /cvmfs/sft.cern.ch/lcg/releases/ROOT/6.26.08-34ede/x86_64-centos7-gcc11-opt/macros/${HOME}/rootlogon.C, output: /cvmfs/sft.cern.ch/lcg/releases/ROOT/6.26.08-34ede/x86_64-centos7-gcc11-opt/macros/${HOME}/rootlogon.C
cling::DynamicLibraryManager::loadLibrary(): libOpenGL.so.0: cannot open shared object file: No such file or directory
cling::DynamicLibraryManager::loadLibrary(): libOpenGL.so.0: cannot open shared object file: No such file or directory
Error in <TUnixSystem::FindDynamicLibrary>: libSingleDualCrystal[.so | .dll | .dylib | .sl | .dl | .a] does not exist in /data/users/snabili/CalVision/DD4HEP_simulation_05282024/DD4hep/lib:/cvmfs/sft.cern.ch/lcg/views/LCG_102b/x86_64-centos7-gcc11-opt/lib64:/cvmfs/sft.cern.ch/lcg/releases/ROOT/6.26.08-34ede/x86_64-centos7-gcc11-opt/lib:/cvmfs/sft.cern.ch/lcg/releases/MCGenerators/thepeg/2.2.3-6cb32/x86_64-centos7-gcc11-opt/lib/ThePEG:/cvmfs/sft.cern.ch/lcg/releases/MCGenerators/herwig++/7.2.3-90caf/x86_64-centos7-gcc11-opt/lib/Herwig:/cvmfs/sft.cern.ch/lcg/views/LCG_102b/x86_64-centos7-gcc11-opt/lib/python3.9/site-packages/jaxlib/mlir/_mlir_libs:/cvmfs/sft.cern.ch/lcg/views/LCG_102b/x86_64-centos7-gcc11-opt/lib/python3.9/site-packages/torch/lib:/cvmfs/sft.cern.ch/lcg/views/LCG_102b/x86_64-centos7-gcc11-opt/lib/python3.9/site-packages/onnxruntime/capi/:/cvmfs/sft.cern.ch/lcg/views/LCG_102b/x86_64-centos7-gcc11-opt/lib/python3.9/site-packages/tensorflow:/cvmfs/sft.cern.ch/lcg/views/LCG_102b/x86_64-centos7-gcc11-opt/lib/python3.9/site-packages/tensorflow/contrib/tensor_forest:/cvmfs/sft.cern.ch/lcg/views/LCG_102b/x86_64-centos7-gcc11-opt/lib/python3.9/site-packages/tensorflow/python/framework:/cvmfs/sft.cern.ch/lcg/releases/java/8u312-80070/x86_64-centos7-gcc11-opt/jre/lib/amd64:/cvmfs/sft.cern.ch/lcg/views/LCG_102b/x86_64-centos7-gcc11-opt/lib64:/cvmfs/sft.cern.ch/lcg/views/LCG_102b/x86_64-centos7-gcc11-opt/lib:/cvmfs/sft.cern.ch/lcg/releases/gcc/11.3.0-ad0f5/x86_64-centos7/lib:/cvmfs/sft.cern.ch/lcg/releases/gcc/11.3.0-ad0f5/x86_64-centos7/lib64:/cvmfs/sft.cern.ch/lcg/releases/binutils/2.37-355ed/x86_64-centos7/lib:/cvmfs/sft.cern.ch/lcg/releases/R/4.1.2-34737/x86_64-centos7-gcc11-opt/lib64/R/library/readr/rcon:/cvmfs/sft.cern.ch/lcg/releases/clhep/2.4.5.1-ebe73/x86_64-centos7-gcc11-opt/lib:/cvmfs/sft.cern.ch/lcg/releases/XercesC/3.2.3-714f6/x86_64-centos7-gcc11-opt/lib:.:/cvmfs/sft.cern.ch/lcg/releases/ROOT/6.26.08-34ede/x86_64-centos7-gcc11-opt/lib:/lib64/tls/x86_64:/lib64/tls:/lib64/x86_64:/lib64:/usr/lib64/tls/x86_64:/usr/lib64/tls:/usr/lib64/x86_64:/usr/lib64
Warning in <TClassTable::Add>: class _Rb_tree_iterator<pair<const int,dd4hep::sim::Geant4Particle*> > already in TClassTable
Warning in <TClassTable::Add>: class _Rb_tree_const_iterator<pair<const int,dd4hep::sim::Geant4Particle*> > already in TClassTable
Warning in <TClassTable::Add>: class dd4hep::sim::SimpleRun already in TClassTable
Warning in <TClassTable::Add>: class dd4hep::sim::SimpleEvent already in TClassTable
Warning in <TClassTable::Add>: class dd4hep::sim::DataExtension already in TClassTable
Warning in <TClassTable::Add>: class dd4hep::sim::Geant4HitData already in TClassTable
Warning in <TClassTable::Add>: class dd4hep::sim::Geant4HitData::MonteCarloContrib already in TClassTable
Warning in <TClassTable::Add>: class dd4hep::sim::Geant4Tracker already in TClassTable
Warning in <TClassTable::Add>: class dd4hep::sim::Geant4Tracker::Hit already in TClassTable
Warning in <TClassTable::Add>: class dd4hep::sim::Geant4Calorimeter already in TClassTable
Warning in <TClassTable::Add>: class dd4hep::sim::Geant4Calorimeter::Hit already in TClassTable
Warning in <TClassTable::Add>: class dd4hep::sim::ParticleExtension already in TClassTable
Warning in <TClassTable::Add>: class dd4hep::sim::Geant4Particle already in TClassTable
Error in <TFile::TFile>: file /data/users/snabili/CalVision/DD4HEP_simulation_05282024/DD4hep/examples/SingleCrystal_cosmic_ray/compact/Root_files/Protons/PbWO4/0811_100_ev/out_0811_-50.root does not exist

 *** Break *** segmentation violation



===========================================================
There was a crash.
This is the entire stack trace of all threads:
===========================================================
#0  0x00002ab76036360c in waitpid () from /lib64/libc.so.6
#1  0x00002ab7602e0f62 in do_system () from /lib64/libc.so.6
#2  0x00002ab75f8fc92c in TUnixSystem::StackTrace() () from /cvmfs/sft.cern.ch/lcg/releases/ROOT/6.26.08-34ede/x86_64-centos7-gcc11-opt/bin/../lib/libCore.so
#3  0x00002ab75f8fa025 in TUnixSystem::DispatchSignals(ESignals) () from /cvmfs/sft.cern.ch/lcg/releases/ROOT/6.26.08-34ede/x86_64-centos7-gcc11-opt/bin/../lib/libCore.so
#4  <signal handler called>
#5  0x00002ab75f4f169a in ?? ()
#6  0x00007ffdd472713f in ?? ()
#7  0x0000000000000001 in ?? ()
#8  0x00002ab75f502800 in ?? ()
#9  0x0000000000000000 in ?? ()
===========================================================


The lines below might hint at the cause of the crash.
You may get help by asking at the ROOT forum https://root.cern/forum
Only if you are really convinced it is a bug in ROOT then please submit a
report at https://root.cern/bugs Please post the ENTIRE stack trace
from above as an attachment in addition to anything else
that might help us fixing this issue.
===========================================================
#5  0x00002ab75f4f169a in ?? ()
#6  0x00007ffdd472713f in ?? ()
#7  0x0000000000000001 in ?? ()
#8  0x00002ab75f502800 in ?? ()
#9  0x0000000000000000 in ?? ()
===========================================================


